# -*- coding: utf-8 -*-
"""CS_Green_Assignment2_Maurel_Kouekam_kouekmau99@gmail.com.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12i_OAWVnoEF62bA6VzYHtavjD-z0Ah2_

# Log File Analysis

### 1- Open the log file such that only a single line at a time is loaded into memory:
"""

def openLogFile(path):
    with open(path) as log_file:
        for log_entry in log_file:
            yield log_entry

path = "/content/drive/MyDrive/ML/part2.log.txt"

log_file = openLogFile(path)

log_file

next(log_file)

"""### 2- Parse the log file and record the fields highlighted above"""

import re

def parseLogFile(log_entry):
    log_data = re.split("\t", log_entry.rstrip())
    r = {}
    r["ts"] = log_data[0]
    r["uid"] = log_data[1]
    r["id.orig_h"] = log_data[2]
    r["id.orig_p"] = log_data[3]
    r["id.resp_h"] = log_data[4]
    r["id.resp_p"] = log_data[5]
    r["trans_depth"] = log_data[6]
    r["method"] = log_data[7]
    r["host"] = log_data[8]
    r["uri"] = log_data[9]
    return r

sample = parseLogFile(next(log_file))
sample

"""### 3- Create a datetime object to record the date"""

#Datetime Object
from datetime import datetime as dt

"""### 4- Find and print the three most commonly seen "host"
"""

from collections import Counter

def getHttpByHost(path):
  r = Counter()
  log_file = openLogFile(path)
  for log_entry in log_file:
    try:
      log_data = parseLogFile(log_entry)
      r.update([log_data['host']])
    except:
      pass
  return r

req = getHttpByHost(path)

print("The three most commonly seen \"host\" are: ",req.most_common()[:3])

"""### 5- Briefly describe these hosts as a comment in your program/notebook. One or two sentences for each is sufficient.

**c2.globonamtics.com**: This host belongs to the "globonamtics.com" domain and may be used for hosting or communication related to the Globonamtics organization or service.

   **ocsp.digicert.com**: This host is used for Online Certificate Status Protocol (OCSP) requests related to certificates issued by DigiCert, a certificate authority.

   **ocsp.sca1b.amazontrust.com**: This host is used for OCSP requests related to certificates issued by Amazon Trust Services, which is part of the Amazon Web Services (AWS) infrastructure.

### 6- Create a plot that shows these three common hosts throughout the record
"""

import matplotlib.pyplot as plt

def plotEvents(events):
  plt.bar(range(len(events)), list(events), align="center")
  plt.show()

plotEvents(req)